server.port: 7777
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  application:
    name: customer-service
  config:
    activate:
      pn-profile: default
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  jpa:
    open-in-view: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    datasource:
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver
      platform: postgres
      schema: classpath:init-schema.sql
      initialization-mode: always
